---
name: Leonardo
surname: Feitosa
position: "PhD Student"
address: "Bren School of Environmental Science and Management, University of California, Santa Barbara"
phone: +55 98 991533001
profilepic: leo.jpg
www: 
email: "lmfeitos@gmail.com"
twitter: @FeitosaManir
github: lmfeitos
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Leonardo Feitosa is a Brazilian researcher focusing on shark and ray conservation"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
```

# Some stuff about me

* 
*
*

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Biological Sciences", "2012-2017", "Universidade Federal do Maranhão", "São Luís, Brazil",
  "Master of Animal Biology", "2019", "Universidade Federal de Pernambuco", "Recife, Brazil",
  "PhD in Environmental Science and Management", "Ongoing (2020)", "University of California", "Santa Barbara, USA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Publications (Needs fixing)

# Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2016, "Best Oral talk", "Carolus Maria Vooren award from the Brazilian Society for the study of Elasmobranchs",
  2020, "Full PhD Fulbright Scholarship", "Awarded with a fully funded PhD from Fulbright Brazil and CAPES"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```

